sudo: false
language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - redis-server

script:
  - make test
  - cargo check --benches

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
