sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - redis-server

script:
  - REDISRS_UNIFIED_TARGET=1 make test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
