before_install:
  - yes | sudo add-apt-repository ppa:rwky/redis
  - sudo apt-get update

install:
  - curl https://static.rust-lang.org/rustup.sh > /tmp/rustup.sh && chmod a+x /tmp/rustup.sh && /tmp/rustup.sh --yes 
  - sudo apt-get -y install redis-server

script:
  - make test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
