sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - mkdir -p /tmp/redis
  - curl http://download.redis.io/releases/redis-3.2.9.tar.gz | tar --strip-components 1 -C /tmp/redis -zx
  - make -C /tmp/redis -j 2
  - make -C /tmp/redis PREFIX=/tmp/redis install

script:
  - PATH=/tmp/redis:$PATH make test

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
