sudo: false
language: rust
cache: cargo

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable

    - rust: beta
      env: RUST_VERSION=beta

    - rust: nightly
      env: RUST_VERSION=nightly

before_install:
  - mkdir -p /tmp/redis
  - curl http://download.redis.io/releases/redis-3.2.9.tar.gz | tar --strip-components 1 -C /tmp/redis -zx
  - make -C /tmp/redis -j 2
  - make -C /tmp/redis PREFIX=/tmp/redis install

script:
  - PATH=/tmp/redis/bin:$PATH make test
  - cargo check --benches
  - |
    [ "$RUST_VERSION" = "nightly" ] && exit 0 # Don't cargo-fmt on nightly
    rustup component add rustfmt
    cargo fmt --all -- --check

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
