sudo: false
language: rust

# Prevents cargo's cache from growing to large, see https://levans.fr/rust_travis_cache.html
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

# This is not a an official ppa but seems to be a well-known one. Replace it if
# we can get Redis 6 from main stream package mananger.
#
# Refs:
# - https://github.com/antirez/redis/issues/1732
# - https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server
before_install: |
  sudo add-apt-repository ppa:chris-lea/redis-server -y
  sudo apt-get update
  sudo apt-get install redis-server=5:6.0.5-1chl1~xenial1 stunnel -y

matrix:
  include:
    - rust: stable
      env: RUST_VERSION=stable COMMAND=test

    - rust: beta
      env: RUST_VERSION=beta COMMAND=test

    - rust: nightly
      env: RUST_VERSION=nightly COMMAND=test

    - rust: stable
      env: COMMAND=lint

script:
  - make $COMMAND
  - cargo check --benches --all-features
  - |
    ([ "$RUST_VERSION" = "nightly" ] || [ "$RUST_VERSION" = "beta" ]) && exit 0 # Don't cargo-fmt on nightly or beta
    make style-check
  - |
    # Remove dev-dependencies so they do not enable features accidentally
    # https://github.com/rust-lang/cargo/issues/4664
    sed -i '/dev-dependencies/,/dev-dependencies/d' Cargo.toml
    cargo build --all-features

notifications:
  email: false
