[package]
name = "redis"
version = "0.6.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["redis", "database"]
description = "Redis driver for Rust."
homepage = "https://github.com/mitsuhiko/redis-rs"
documentation = "http://mitsuhiko.github.io/redis-rs/"
license = "BSD-3-Clause"
readme = "README.md"

#[dependencies.sha1]
#git = "https://github.com/mitsuhiko/rust-sha1.git"
#
#[dependencies.url]
#git = "https://github.com/servo/rust-url"

[features]
with-rustc-json = ["rustc-serialize"]
with-unix-sockets = ["unix_socket"]

[dependencies]
sha1 = "0.2.0"
url = "1.1"
rustc-serialize = { version = "0.3.16", optional = true }
unix_socket = { version = "0.5.0", optional = true }
