[package]
name = "redis-rs"
version = "0.3.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
keywords = ["redis", "database"]
description = "Redis driver for Rust."
license = "BSD-3-Clause"

[dependencies.sha1]
git = "https://github.com/mitsuhiko/rust-sha1.git"

[dependencies.url]
git = "https://github.com/servo/rust-url"

[lib]
name = "redis"
path = "src/lib.rs"
