pre-release-replacements = [ {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"}, {file="CHANGELOG.md", search="HEAD", replace="{{version}}"}, {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"}, {file="README.md", search="{{prev_version}}", replace="{{version}}"} ]
tag-prefix = ""
